using System;
using System.IO;
using System.Linq;
using UndertaleModLib.Models;
using UndertaleModLib.Util;
EnsureDataLoaded();
string[] names = new[] { "ag_open_shift_chapter", "ag_open_shift_start", "ag_bridge_controller", "ag_safe_text" };
foreach (string name in names) if (Data.GameObjects.ByName(name) is null) throw new Exception("Missing object: " + name);
if (Data.GameObjects.ByName("ag_open_shift_chapter").Sprite?.Name?.Content != "blue_chapter") throw new Exception("Chapter sprite mismatch");
if (Data.GameObjects.ByName("ag_open_shift_start").Sprite?.Name?.Content != "yellow_chapter") throw new Exception("Start sprite mismatch");
string[] code = new[] { "gml_Object_ag_open_shift_chapter_Create_0", "gml_Object_ag_open_shift_chapter_Step_0", "gml_Object_ag_open_shift_chapter_Draw_0", "gml_Object_ag_open_shift_start_Create_0", "gml_Object_ag_open_shift_start_Step_0", "gml_Object_ag_open_shift_start_Draw_0", "gml_Object_ag_bridge_controller_Create_0", "gml_Object_ag_bridge_controller_Step_0", "gml_Object_ag_bridge_controller_Other_62", "gml_Object_ag_safe_text_Create_0", "gml_Object_ag_safe_text_Draw_0" };
foreach (string name in code) if (Data.Code.ByName(name) is null) throw new Exception("Missing code: " + name);
if (Data.Code.ByName("gml_Object_prologuechapter_Step_0") is null) throw new Exception("Missing chapter entrypoint");
ScriptMessage("Open Shift patched data verified.");
