using System;
using System.IO;
using System.Linq;
using UndertaleModLib.Models;
using UndertaleModLib.Util;
EnsureDataLoaded();
GlobalDecompileContext context = new GlobalDecompileContext(Data);
Underanalyzer.Decompiler.IDecompileSettings settings = Data.ToolInfo.DecompilerSettings;
string Decompile(string name) => new Underanalyzer.Decompiler.DecompileContext(
    context, Data.Code.ByName(name), settings
).DecompileToString();
string[] names = new[] { "ag_open_shift_chapter", "ag_open_shift_start", "ag_bridge_controller" };
foreach (string name in names) if (Data.GameObjects.ByName(name) is null) throw new Exception("Missing object: " + name);
if (Data.GameObjects.ByName("ag_open_shift_chapter").Sprite?.Name?.Content != "blue_chapter") throw new Exception("Chapter sprite mismatch");
if (Data.GameObjects.ByName("ag_open_shift_start").Sprite?.Name?.Content != "yellow_chapter") throw new Exception("Start sprite mismatch");
string[] code = new[] { "gml_Object_ag_open_shift_chapter_Create_0", "gml_Object_ag_open_shift_chapter_Step_0", "gml_Object_ag_open_shift_start_Create_0", "gml_Object_ag_open_shift_start_Step_0", "gml_Object_ag_bridge_controller_Create_0", "gml_Object_ag_bridge_controller_Step_0", "gml_Object_ag_bridge_controller_Other_62" };
foreach (string name in code) if (Data.Code.ByName(name) is null) throw new Exception("Missing code: " + name);
if (Data.Code.ByName("gml_Object_prologuechapter_Step_0") is null) throw new Exception("Missing chapter entrypoint");
if (Data.Code.ByName("gml_Object_extrachapter_text_Draw_0") is null) throw new Exception("Missing chapter text draw entrypoint");
if (Data.Code.ByName("gml_Object_dialog_control_Create_0") is null) throw new Exception("Missing bar scene entrypoint");
string chapterDraw = Decompile("gml_Object_extrachapter_text_Draw_0");
string controllerCreate = Decompile("gml_Object_ag_bridge_controller_Create_0");
string controllerStep = Decompile("gml_Object_ag_bridge_controller_Step_0");
string controllerHttp = Decompile("gml_Object_ag_bridge_controller_Other_62");
if (!chapterDraw.Contains("O.S.")) throw new Exception("Short chapter label was missing");
if (!controllerCreate.Contains("session_id")) throw new Exception("Unique runtime session was missing");
if (!controllerStep.Contains("continued_in_bar")) throw new Exception("Continuous bar outcome was missing");
if (!controllerHttp.Contains("/v1/scenes/open")) throw new Exception("Next-scene request was missing");
string controllerCode = controllerCreate + controllerStep + controllerHttp;
if (controllerCode.Contains("sprite_jill")) throw new Exception("Jill must remain the player viewpoint");
if (controllerCode.Contains("out_to_title")) throw new Exception("Controller must not force a title return");
ScriptMessage("Open Shift patched data verified.");
